#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'pwm_2', class 'altera_avalon_pio'
 * The macros are prefixed with 'PWM_2_'.
 * The prefix is the slave descriptor.
 */
#define PWM_2_COMPONENT_TYPE altera_avalon_pio
#define PWM_2_COMPONENT_NAME pwm_2
#define PWM_2_BASE 0x0
#define PWM_2_SPAN 64
#define PWM_2_END 0x3f
#define PWM_2_BIT_CLEARING_EDGE_REGISTER 0
#define PWM_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PWM_2_CAPTURE 0
#define PWM_2_DATA_WIDTH 21
#define PWM_2_DO_TEST_BENCH_WIRING 0
#define PWM_2_DRIVEN_SIM_VALUE 0
#define PWM_2_EDGE_TYPE NONE
#define PWM_2_FREQ 50000000
#define PWM_2_HAS_IN 0
#define PWM_2_HAS_OUT 1
#define PWM_2_HAS_TRI 0
#define PWM_2_IRQ_TYPE NONE
#define PWM_2_RESET_VALUE 80000

/*
 * Macros for device 'ccw_2', class 'altera_avalon_pio'
 * The macros are prefixed with 'CCW_2_'.
 * The prefix is the slave descriptor.
 */
#define CCW_2_COMPONENT_TYPE altera_avalon_pio
#define CCW_2_COMPONENT_NAME ccw_2
#define CCW_2_BASE 0x10
#define CCW_2_SPAN 64
#define CCW_2_END 0x4f
#define CCW_2_IRQ 4
#define CCW_2_BIT_CLEARING_EDGE_REGISTER 1
#define CCW_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CCW_2_CAPTURE 1
#define CCW_2_DATA_WIDTH 32
#define CCW_2_DO_TEST_BENCH_WIRING 0
#define CCW_2_DRIVEN_SIM_VALUE 0
#define CCW_2_EDGE_TYPE FALLING
#define CCW_2_FREQ 50000000
#define CCW_2_HAS_IN 1
#define CCW_2_HAS_OUT 0
#define CCW_2_HAS_TRI 0
#define CCW_2_IRQ_TYPE EDGE
#define CCW_2_RESET_VALUE 0

/*
 * Macros for device 'cw_2', class 'altera_avalon_pio'
 * The macros are prefixed with 'CW_2_'.
 * The prefix is the slave descriptor.
 */
#define CW_2_COMPONENT_TYPE altera_avalon_pio
#define CW_2_COMPONENT_NAME cw_2
#define CW_2_BASE 0x20
#define CW_2_SPAN 64
#define CW_2_END 0x5f
#define CW_2_IRQ 3
#define CW_2_BIT_CLEARING_EDGE_REGISTER 1
#define CW_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CW_2_CAPTURE 1
#define CW_2_DATA_WIDTH 32
#define CW_2_DO_TEST_BENCH_WIRING 0
#define CW_2_DRIVEN_SIM_VALUE 0
#define CW_2_EDGE_TYPE FALLING
#define CW_2_FREQ 50000000
#define CW_2_HAS_IN 1
#define CW_2_HAS_OUT 0
#define CW_2_HAS_TRI 0
#define CW_2_IRQ_TYPE EDGE
#define CW_2_RESET_VALUE 0

/*
 * Macros for device 'pwm_3', class 'altera_avalon_pio'
 * The macros are prefixed with 'PWM_3_'.
 * The prefix is the slave descriptor.
 */
#define PWM_3_COMPONENT_TYPE altera_avalon_pio
#define PWM_3_COMPONENT_NAME pwm_3
#define PWM_3_BASE 0x30
#define PWM_3_SPAN 64
#define PWM_3_END 0x6f
#define PWM_3_BIT_CLEARING_EDGE_REGISTER 0
#define PWM_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PWM_3_CAPTURE 0
#define PWM_3_DATA_WIDTH 21
#define PWM_3_DO_TEST_BENCH_WIRING 0
#define PWM_3_DRIVEN_SIM_VALUE 0
#define PWM_3_EDGE_TYPE NONE
#define PWM_3_FREQ 50000000
#define PWM_3_HAS_IN 0
#define PWM_3_HAS_OUT 1
#define PWM_3_HAS_TRI 0
#define PWM_3_IRQ_TYPE NONE
#define PWM_3_RESET_VALUE 80000

/*
 * Macros for device 'ccw_3', class 'altera_avalon_pio'
 * The macros are prefixed with 'CCW_3_'.
 * The prefix is the slave descriptor.
 */
#define CCW_3_COMPONENT_TYPE altera_avalon_pio
#define CCW_3_COMPONENT_NAME ccw_3
#define CCW_3_BASE 0x40
#define CCW_3_SPAN 128
#define CCW_3_END 0xbf
#define CCW_3_IRQ 6
#define CCW_3_BIT_CLEARING_EDGE_REGISTER 1
#define CCW_3_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CCW_3_CAPTURE 1
#define CCW_3_DATA_WIDTH 32
#define CCW_3_DO_TEST_BENCH_WIRING 0
#define CCW_3_DRIVEN_SIM_VALUE 0
#define CCW_3_EDGE_TYPE FALLING
#define CCW_3_FREQ 50000000
#define CCW_3_HAS_IN 1
#define CCW_3_HAS_OUT 0
#define CCW_3_HAS_TRI 0
#define CCW_3_IRQ_TYPE EDGE
#define CCW_3_RESET_VALUE 0

/*
 * Macros for device 'cw_3', class 'altera_avalon_pio'
 * The macros are prefixed with 'CW_3_'.
 * The prefix is the slave descriptor.
 */
#define CW_3_COMPONENT_TYPE altera_avalon_pio
#define CW_3_COMPONENT_NAME cw_3
#define CW_3_BASE 0x60
#define CW_3_SPAN 128
#define CW_3_END 0xdf
#define CW_3_IRQ 5
#define CW_3_BIT_CLEARING_EDGE_REGISTER 1
#define CW_3_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CW_3_CAPTURE 1
#define CW_3_DATA_WIDTH 32
#define CW_3_DO_TEST_BENCH_WIRING 0
#define CW_3_DRIVEN_SIM_VALUE 0
#define CW_3_EDGE_TYPE FALLING
#define CW_3_FREQ 50000000
#define CW_3_HAS_IN 1
#define CW_3_HAS_OUT 0
#define CW_3_HAS_TRI 0
#define CW_3_IRQ_TYPE EDGE
#define CW_3_RESET_VALUE 0

/*
 * Macros for device 'cw_4', class 'altera_avalon_pio'
 * The macros are prefixed with 'CW_4_'.
 * The prefix is the slave descriptor.
 */
#define CW_4_COMPONENT_TYPE altera_avalon_pio
#define CW_4_COMPONENT_NAME cw_4
#define CW_4_BASE 0x80
#define CW_4_SPAN 128
#define CW_4_END 0xff
#define CW_4_IRQ 7
#define CW_4_BIT_CLEARING_EDGE_REGISTER 1
#define CW_4_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CW_4_CAPTURE 1
#define CW_4_DATA_WIDTH 32
#define CW_4_DO_TEST_BENCH_WIRING 0
#define CW_4_DRIVEN_SIM_VALUE 0
#define CW_4_EDGE_TYPE FALLING
#define CW_4_FREQ 50000000
#define CW_4_HAS_IN 1
#define CW_4_HAS_OUT 0
#define CW_4_HAS_TRI 0
#define CW_4_IRQ_TYPE EDGE
#define CW_4_RESET_VALUE 0

/*
 * Macros for device 'pwm_4', class 'altera_avalon_pio'
 * The macros are prefixed with 'PWM_4_'.
 * The prefix is the slave descriptor.
 */
#define PWM_4_COMPONENT_TYPE altera_avalon_pio
#define PWM_4_COMPONENT_NAME pwm_4
#define PWM_4_BASE 0xa0
#define PWM_4_SPAN 64
#define PWM_4_END 0xdf
#define PWM_4_BIT_CLEARING_EDGE_REGISTER 0
#define PWM_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PWM_4_CAPTURE 0
#define PWM_4_DATA_WIDTH 21
#define PWM_4_DO_TEST_BENCH_WIRING 0
#define PWM_4_DRIVEN_SIM_VALUE 0
#define PWM_4_EDGE_TYPE NONE
#define PWM_4_FREQ 50000000
#define PWM_4_HAS_IN 0
#define PWM_4_HAS_OUT 1
#define PWM_4_HAS_TRI 0
#define PWM_4_IRQ_TYPE NONE
#define PWM_4_RESET_VALUE 80000

/*
 * Macros for device 'ccw_4', class 'altera_avalon_pio'
 * The macros are prefixed with 'CCW_4_'.
 * The prefix is the slave descriptor.
 */
#define CCW_4_COMPONENT_TYPE altera_avalon_pio
#define CCW_4_COMPONENT_NAME ccw_4
#define CCW_4_BASE 0xb0
#define CCW_4_SPAN 64
#define CCW_4_END 0xef
#define CCW_4_IRQ 8
#define CCW_4_BIT_CLEARING_EDGE_REGISTER 1
#define CCW_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CCW_4_CAPTURE 1
#define CCW_4_DATA_WIDTH 32
#define CCW_4_DO_TEST_BENCH_WIRING 0
#define CCW_4_DRIVEN_SIM_VALUE 0
#define CCW_4_EDGE_TYPE FALLING
#define CCW_4_FREQ 50000000
#define CCW_4_HAS_IN 1
#define CCW_4_HAS_OUT 0
#define CCW_4_HAS_TRI 0
#define CCW_4_IRQ_TYPE EDGE
#define CCW_4_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1769519109

/*
 * Macros for device 'led_pio_pwm', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_PWM_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_PWM_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_PWM_COMPONENT_NAME led_pio_pwm
#define LED_PIO_PWM_BASE 0x10040
#define LED_PIO_PWM_SPAN 64
#define LED_PIO_PWM_END 0x1007f
#define LED_PIO_PWM_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_PWM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_PWM_CAPTURE 0
#define LED_PIO_PWM_DATA_WIDTH 21
#define LED_PIO_PWM_DO_TEST_BENCH_WIRING 0
#define LED_PIO_PWM_DRIVEN_SIM_VALUE 0
#define LED_PIO_PWM_EDGE_TYPE NONE
#define LED_PIO_PWM_FREQ 50000000
#define LED_PIO_PWM_HAS_IN 0
#define LED_PIO_PWM_HAS_OUT 1
#define LED_PIO_PWM_HAS_TRI 0
#define LED_PIO_PWM_IRQ_TYPE NONE
#define LED_PIO_PWM_RESET_VALUE 80000

/*
 * Macros for device 'dipsw_pio_cw', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_CW_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_CW_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_CW_COMPONENT_NAME dipsw_pio_cw
#define DIPSW_PIO_CW_BASE 0x10080
#define DIPSW_PIO_CW_SPAN 64
#define DIPSW_PIO_CW_END 0x100bf
#define DIPSW_PIO_CW_IRQ 0
#define DIPSW_PIO_CW_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_CW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CW_CAPTURE 1
#define DIPSW_PIO_CW_DATA_WIDTH 32
#define DIPSW_PIO_CW_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_CW_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_CW_EDGE_TYPE FALLING
#define DIPSW_PIO_CW_FREQ 50000000
#define DIPSW_PIO_CW_HAS_IN 1
#define DIPSW_PIO_CW_HAS_OUT 0
#define DIPSW_PIO_CW_HAS_TRI 0
#define DIPSW_PIO_CW_IRQ_TYPE EDGE
#define DIPSW_PIO_CW_RESET_VALUE 0

/*
 * Macros for device 'button_pio_ccw', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_CCW_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_CCW_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_CCW_COMPONENT_NAME button_pio_ccw
#define BUTTON_PIO_CCW_BASE 0x100c0
#define BUTTON_PIO_CCW_SPAN 64
#define BUTTON_PIO_CCW_END 0x100ff
#define BUTTON_PIO_CCW_IRQ 1
#define BUTTON_PIO_CCW_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_CCW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CCW_CAPTURE 1
#define BUTTON_PIO_CCW_DATA_WIDTH 32
#define BUTTON_PIO_CCW_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_CCW_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_CCW_EDGE_TYPE FALLING
#define BUTTON_PIO_CCW_FREQ 50000000
#define BUTTON_PIO_CCW_HAS_IN 1
#define BUTTON_PIO_CCW_HAS_OUT 0
#define BUTTON_PIO_CCW_HAS_TRI 0
#define BUTTON_PIO_CCW_IRQ_TYPE EDGE
#define BUTTON_PIO_CCW_RESET_VALUE 0

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 32
#define JTAG_UART_END 0x2001f
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'reset_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'RESET_PIO_'.
 * The prefix is the slave descriptor.
 */
#define RESET_PIO_COMPONENT_TYPE altera_avalon_pio
#define RESET_PIO_COMPONENT_NAME reset_pio
#define RESET_PIO_BASE 0x40000
#define RESET_PIO_SPAN 64
#define RESET_PIO_END 0x4003f
#define RESET_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define RESET_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RESET_PIO_CAPTURE 0
#define RESET_PIO_DATA_WIDTH 1
#define RESET_PIO_DO_TEST_BENCH_WIRING 0
#define RESET_PIO_DRIVEN_SIM_VALUE 0
#define RESET_PIO_EDGE_TYPE NONE
#define RESET_PIO_FREQ 50000000
#define RESET_PIO_HAS_IN 0
#define RESET_PIO_HAS_OUT 1
#define RESET_PIO_HAS_TRI 0
#define RESET_PIO_IRQ_TYPE NONE
#define RESET_PIO_RESET_VALUE 1


#endif /* _ALTERA_HPS_0_H_ */
